// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlite

import (
	"time"
)

type Muse struct {
	Hash   string
	Rating int64
}

type Reminder struct {
	ID        int64
	MessageID string
	UserID    string
	ChannelID string
	RemindAt  time.Time
}
